DevEntities:
 - !DevEntity
    name: Zone
    business_key:
         - LocationID
    fields: 
        LocationID:
            type: int4
            taille: 10    
        Borough:
            type: varchar
            taille: 100
        Zone:
            type: Varchar
            taille: 100
        Service_Zone:
            type: Varchar
            taille: 100

Links: