Workspaces:
 - !Workspace
    repository: C:\Users\TJSAMBADZUGUIA\Desktop\Taxi_NYK\wrk\workspace
Others:
    log_format: text
    archive_repo: C:\Users\TJSAMBADZUGUIA\Desktop\Taxi_NYK\wrk\archive
    error_repo: C:\Users\TJSAMBADZUGUIA\Desktop\Taxi_NYK\wrk\error
    log_repo: C:\Users\TJSAMBADZUGUIA\Desktop\Taxi_NYK\log
         

